# Generated by Django 5.0.2 on 2024-04-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.TextField(default='Default Description')),
                ('offer', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('img', models.ImageField(blank=True, default='null', null=True, upload_to='categories')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
