# Generated by Django 5.0.2 on 2024-04-16 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=10)),
                ('display_size', models.IntegerField()),
                ('camera', models.CharField(blank=True, max_length=20, null=True)),
                ('network', models.BooleanField()),
                ('smart', models.BooleanField()),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='products')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.main_category')),
            ],
        ),
    ]
